version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    depends_on:
      - migrations

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: neuralnetwork_data:2:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: kafka.controller=WARN,kafka.foo.bar=DEBUG
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      
  db:
    image: postgres:12.1
    container_name: client-service-db
    ports:
      - 36000:5432
    environment: 
      POSTGRES_PASSWORD: "postgres"

  migrations:
    image: docker.pkg.github.com/louiechannel/client-service-db/client-service-db:1.0.1
    container_name: client-service-migrations
    environment: 
      CONNECTION_STRING: "Host=db; Username=postgres; Password=postgres"
      DELAY: 3000
    depends_on:
      - db
      
  dumperservice:
    image: docker.pkg.github.com/louiechannel/dumper-service/dumper-service:0.1.0
    depends_on:
      - kafka
    container_name: dumperservice
    restart: on-failure
    command: >
      /bin/bash -c "
        sleep 100;
      "
    environment:
      ASPNETCORE_ENVIRONMENT: Development
     
  streamservice:
    image: docker.pkg.github.com/louiechannel/stream-service/stream-service:0.1.0
    depends_on:
      - kafka
    container_name: streamservice
    restart: on-failure
    command: >
      /bin/bash -c "
        sleep 110;
      "
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5005:5005
      
  streamserviceclient:
    image: docker.pkg.github.com/louiechannel/stream-service/stream-client-service:0.1.0
    depends_on:
      - streamservice
    container_name: streamserviceclient
    restart: on-failure
  
  neuralnetworkservice:
    image: docker.pkg.github.com/louiechannel/neuralnetwork-service/neuralnetwork-service:0.1.0
    depends_on:
      - kafka
    container_name: neuralnetworkservice
    restart: on-failure

  neuralnetworkservice2:
    image: docker.pkg.github.com/louiechannel/neuralnetwork-service/neuralnetwork-service:0.1.0
    depends_on:
      - kafka
    container_name: neuralnetworkservice2
    restart: on-failure
