version: '3'

networks:
  clientservice:
  
services:
  db:
    image: postgres:12.1
    container_name: client-service-db
    ports:
      - 36000:5432
    environment: 
      POSTGRES_PASSWORD: "postgres"
    networks:
      - clientservice

  migrations:
    image: docker.pkg.github.com/louiechannel/client-service-db/client-service-db:1.0.1
    container_name: client-service-migrations
    environment: 
      CONNECTION_STRING: "Host=db; Username=postgres; Password=postgres"
      DELAY: 3000
    depends_on:
      - db
    networks:
      - clientservice  
